### ISSUE TITLE
Request: Ability to Highlight single sections

### ISSUE THREAD

**Issue by Brockenstein** [radancyco/tb-ajd-template#2]
Currently, the in page navigation highlights the sections visible in the viewpoint. You can turn this feature off. There is a request to have the ability for it to only highlight one section at a time. Possibly have the highlight trigger once the element is halfway in the viewpoint.

**Comment by Brockenstein** [comment]
Enhancement live now if you want only one item in the navigation to highlight at a time during scrolling all you need to do is add the class singular-highlighting to ajd_navigation. What will happen is only the top most section that is in the viewport will be highlighted. As seen here:
https://www.screencast.com/t/AKkZLVSfG3q

Adam please confirm this is what you need by testing on the skeleton version.

**Comment by dfoerst** [comment]
When I add the class singular-highlighting to the navigation it breaks the Success Profile bars from sliding out.

**Comment by Brockenstein** [comment]
Thanks @dfoerst for reporting that. I believe I have fixed the issue. Please test and report back. Also please confirm that this is how you expect this feature to work. Adam is a bit busy but if you sign off on it we can close this ticket.

**Comment by dfoerst** [comment]
Thanks @Brockenstein, this is working now. It is how this should work. Thanks again,

**Comment by Brockenstein** [comment]
Since all issues with enhancement has been resolved and enhancement is working as expected I am closing this ticket.
