### ISSUE TITLE
Accessibility: Update Video Play Button

### ISSUE THREAD

**Issue by michaelspellacy** [radancyco/tb-ajd-template#21]
@Brockenstein Could you please update the video play button to be an actual button instead of a link? 

Remember the rule:  buttons perform actions and links take us to places. The play button does the former. Changing it to button will be more AT friendly. 

Also, feel free to use aria-label on that button instead of using the old accessibly hidden (.wai) technique. 

<button ... aria-label="Now Hiring .NET Full Stack Developer (Video)" ... ></button>

Thanks!

**Comment by Brockenstein** [comment]
453aa89 and https://github.com/tmpworldwide/tmp-custom-imports/commit/16499a14708e3487e0fd4de5a25c0722bb931ebf resolved this issue

**Comment by michaelspellacy** [comment]
Looks good! Thx!
